[package]
name = "astro_utils"
version = "0.1.0"
edition = "2021"

[lib]
name         = "astro_utils"
crate-type   = ["rlib"]

[dependencies]
forward_ref_generic = "0.2.0" # Auto-generating std operations on structs
serde = { version = "1.0", features = ["derive"] } # (De)Serialization
reqwest = { version = "0.11", features = ["blocking"] } # Downloading files
