name: Debug Build
on: 
  [push]
  schedule:
    - cron: "0 0 * * 6" # every saturday at 00:00 UTC

jobs:
  debugBuild:
    uses: ./.github/workflows/_build.yml
    with:
      isRelease: ${{ github.ref == 'refs/heads/main' }}
